source 'https://rubygems.org'

gem 'rake'
gem 'highline'
gem 'kitchen-puppet'
gem 'kitchen-ec2'
gem 'kitchen-inspec'
gem 'kitchen-sync'
gem 'kitchen-vagrant'
gem 'inspec-bin', '~> 4.0'
gem 'librarian-puppet'
gem 'inspec_tools'